### ISSUE TITLE
fix groupId to match naming convention

### ISSUE THREAD

**Issue by jmcampanini** [palantir/gradle-launch-config-plugin#31]
we should change the groupId to match our naming convention: `com.palantir.<product>`.

in this case it should be:

* groupId: `com.palantir.launchconfig`
* pluginId: `com.palantir.launch-config`

**Comment by qinfchen** [comment]
I am indifferent. There are plugins that using com.palantir as group id. Take a look at the baseline and Jacoco. If we are pushing for a convention, all plugins should use the same convention. Currently, it is not the case.

On Sep 9, 2016, at 4:35 PM, Javier Campanini <notifications@github.com<mailto:notifications@github.com>> wrote:


we should change the groupId to match our naming convention: com.palantir.<product>.

in this case it should be:

  *   groupId: com.palantir.launchconfig
  *   pluginId: com.palantir.launch-config
